#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ARG BUILD_CONFIGURATION=Debug
EXPOSE 80

WORKDIR /src/

#COPY "HMI.API/HMI.sln" "HMI.API/HMI.sln"
COPY "HMI.API/HMI.sln" "./HMI.API/"

COPY "HMI.API/HMI.API/*.csproj" "HMI.API/HMI.API/"
COPY "HMI.API/Tests/HMI.API.Tests/*.csproj" "HMI.API/Tests/HMI.API.Tests/"
COPY "HMI.API/HMI.API.DataAccess/*.csproj" "HMI.API/HMI.API.DataAccess/"
COPY "HMI.API/HMI.API.Services/*.csproj" "HMI.API/HMI.API.Services/"
COPY "HMI.API/HMI.API.Infrastructure/*.csproj" "HMI.API/HMI.API.Infrastructure/"

RUN dotnet restore "HMI.API/HMI.sln"

COPY . .
WORKDIR "/src/HMI.API/HMI.API"
RUN dotnet build "HMI.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
# this env variable avoid default ports (http:5000 and https:5001), which fail to open in the docker image
# WARNING: when we activate https, port 80 stops working (I don't know why). You can enter swagger UI but
# all the controller actions fail to execute.
# ENV ASPNETCORE_URLS=https://+:443;http://+:80
ENV ASPNETCORE_URLS=http://+:80


WORKDIR /app/build
ENTRYPOINT ["dotnet", "HMI.API.dll"]